server:
  port: 8072


spring:
  cloud:
    stream:
      bindings:
        input1:
          destination: com.mygaienko.rabbitmqpractice
          group: post1
        input3:
          destination: com.mygaienko.rabbitmqpractice1
          bindingRoutingKey: post3
          consumer:
            exchangeType: direct
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      default-binder: local_rabbit