server:
  port: 8071


spring:
  cloud:
    stream:
      bindings:
        input1:
          destination: com.mygaienko.rabbitmqpractice
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      default-binder: local_rabbit