server:
  port: ${server_port:8071}

consumer.index: ${instance_index:0}

spring:
  cloud:
    stream:
      instanceIndex: ${instance_index:0}

      bindings:
        input1:
          destination: com.mygaienko.rabbitmqpractice
          group: post1

        input2:
          destination: com.mygaienko.rabbitmqpractice
          group: post2

        input3:
          destination: com.mygaienko.rabbitmqpractice1
          bindingRoutingKey: post3
          consumer.exchangeType: direct

        input4:
          destination: com.mygaienko.rabbitmqpractice.partitioned
          group: doPart
          consumer.partitioned: true

        input41:
          destination: com.mygaienko.rabbitmqpractice.partitioned
          group: doPart1

        input42:
          destination: com.mygaienko.rabbitmqpractice.partitioned
          group: doPart2
          consumer.acknowledge-mode: MANUAL

        input5Topic:
          destination: com.mygaienko.rabbitmqpractice.topic

      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      default-binder: local_rabbit