server:
  port: 8070


spring:
  cloud:
    stream:

      bindings:
        output1:
          destination: com.mygaienko.rabbitmqpractice
          producer:
            requiredGroups: post1

        output2:
          destination: com.mygaienko.rabbitmqpractice
          producer:
            requiredGroups: post2

        output3:
          destination: com.mygaienko.rabbitmqpractice1
          producer:
            exchangeType: direct
            routingKeyExpression: headers.type
          bindingRoutingKey: post3

        output4:
          destination: com.mygaienko.rabbitmqpractice.partitioned
          group: doPart
          producer:
            partitionKeyExpression: payload.id
            partitionCount: 2

      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      default-binder: local_rabbit
  activemq:
    pool:
      use-anonymous-producers:
