server:
  port: 8070


spring:
  cloud:
    stream:
      bindings:
#        input:
#          destination: queue.log.messages
#          binder: local_rabbit
        output1:
          destination: com.mygaienko.rabbitmqpractice
#          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      default-binder: local_rabbit
